-- ======================================================================
--  JMC apply, part 4 of 5
--
--  GENERATED. Run the parts IN ORDER, each on its own, letting each
--  finish before starting the next. Safe to run more than once.
--
--  These exist because the single combined file is too large to paste
--  into the Supabase SQL editor without being truncated.
-- ======================================================================

begin;
-- Energy & Petrochemical
delete from public.sections where page_id = (select id from public.pages where slug = '/industries/energy-petrochemical');
insert into public.sections (page_id, key, type, tone, data, position) select id, 'hero', 'heroSplit', NULL, '{"eyebrow":"Energy & Petrochemical","heading":"SEO for Energy and Petrochemical Suppliers","body":"Buyers in this sector search by specification, not by adjective. The work is making a business findable in the exact technical language its customers already use.","primaryCta":{"label":"Request a Visibility Review","href":"/contact"},"secondaryCta":{"label":"View Monthly SEO Packages","href":"/monthly-seo-packages"},"showcase":[{"kind":"channels","label":"How buyers search","title":"By Specification","items":["Standards and materials","Part numbers","Compliance requirements","Never adjectives"]},{"kind":"coverage","label":"Who is searching","title":"Three People, One Purchase","items":["Engineer","Procurement","Approver"]}]}'::jsonb, 0 from public.pages where slug = '/industries/energy-petrochemical';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'who-this-is-for', 'cardGrid', 'surface', '{"variant":"split","columns":3,"eyebrow":"Who This Is For","heading":"Suppliers and Service Firms","body":"The kinds of business this applies to. Naming a category is not a claim of expertise in it.","cards":[{"title":"Oil & Gas Field Services & Logistics","icon":"hard-hat","body":"Contracted on capability and compliance, and often searched for during a turnaround or an outage."},{"title":"Petrochemical Plant Services & Contracting","icon":"factory","body":"Qualified long before any conversation, on certifications, safety record and plant experience."},{"title":"Industrial Equipment & Supplies","icon":"layers","body":"Found by part number, specification and standard far more often than by company name."}]}'::jsonb, 1 from public.pages where slug = '/industries/energy-petrochemical';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'search-behaviour', 'featureSplit', 'white', '{"align":"left","eyebrow":"Search Behaviour","heading":"What Search Looks Like in Energy","body":"The searches are technical and unglamorous. A procurement manager or an engineer types a specification, a standard, a material or a part number, and the pages that win are the ones that carry those terms in a form a search engine can read. Marketing language actively hurts here, because nobody is searching for a phrase like world-class solutions.\n\nThe cycle is long, often months, and rarely involves one person. An engineer shortlists, procurement checks compliance, and a manager approves, and each of those people arrives through a different search. Competition is regional and national rather than local, which is what puts most of this sector in the Traditional lane, though a small field-service business working one area is a genuine Local engagement.","groups":[{"title":"Specifications, not adjectives","icon":"code","body":"Standards, materials and part numbers are the search terms. Pages have to contain them plainly."},{"title":"Several searchers, one purchase","icon":"users","body":"Technical, compliance and commercial questions each need their own page rather than one overview."},{"title":"Months, not minutes","icon":"calendar","body":"A long cycle means early visibility work shows up in enquiries much later than it shows up in traffic."}]}'::jsonb, 2 from public.pages where slug = '/industries/energy-petrochemical';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'how-it-works', 'cardGrid', 'surface', '{"variant":"cards","columns":2,"eyebrow":"Where to Start","heading":"Two Ways In, Sorted by Reach","body":"The method does not change with the industry. What changes is the search language, the priorities, and what a single lead is worth. Which service fits a energy & petrochemical business comes down to where it competes, not how big it is.","cards":[{"title":"Local SEO","icon":"map-pin","body":"For businesses competing for customers in a defined area, however many locations they run in it.","cta":{"label":"Explore Local SEO","href":"/local-seo-services"}},{"title":"Traditional SEO","icon":"globe","body":"For businesses competing across multiple markets, multiple service lines, or genuinely competitive search.","cta":{"label":"Explore Traditional SEO","href":"/traditional-seo-services"}}]}'::jsonb, 3 from public.pages where slug = '/industries/energy-petrochemical';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'monthly-recap', 'reportingBlock', 'white', '{"eyebrow":"Reporting","heading":"The Monthly Recap","body":"The same four questions every month, whatever the industry.","did":"The specific work completed that month, named task by task.","why":"Why that work was the priority ahead of everything else in the queue.","changed":"What moved, reported honestly, including the months where little did.","next":"Next month''s priorities, so nothing in the following recap is a surprise.","cta":{"label":"See How JMC Reports SEO Progress","href":"/seo-reporting"}}'::jsonb, 4 from public.pages where slug = '/industries/energy-petrochemical';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'faq', 'faq', 'surface', '{"eyebrow":"Questions","heading":"Energy & Petrochemical Questions","items":[{"question":"Does SEO work when there are only a handful of real buyers?","answer":"It can, because the value of one contract is high enough that a small number of the right visitors justifies the work. It also changes what gets tracked: a narrow, technical keyword set matters far more than total traffic."},{"question":"How is technical content produced without in-house expertise?","answer":"By working from your specifications, datasheets and existing documentation rather than inventing them. Nothing technical is published without your review, because a wrong specification on a page costs more than a missing one."},{"question":"Is this Local or Traditional SEO?","answer":"Usually Traditional, because buyers are spread across markets. A field-service business working one area is a Local engagement, and location count never decides it. Reach does."},{"question":"Which service fits a business like this?","answer":"It depends on reach rather than size. If the customers are in a defined area, that is Local SEO, however many locations are involved. If the business competes across several markets or service lines, that is Traditional SEO. A visibility review sorts it in one conversation."},{"question":"Does JMC specialise in energy & petrochemical?","answer":"No, and that is deliberate. A specialist charges for pattern-matching from other clients in your sector, which JMC does not pretend to have yet. What is on offer instead is a method that works regardless of sector, and reporting clear enough that you can see whether it is working."}],"cta":{"label":"Request a Visibility Review","href":"/contact"}}'::jsonb, 5 from public.pages where slug = '/industries/energy-petrochemical';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'final-cta', 'finalCta', NULL, '{"heading":"Start With a Visibility Review","body":"Where the business appears today, which searches it is missing, and which of those gaps is worth closing first.","primaryCta":{"label":"Request a Visibility Review","href":"/contact"},"secondaryCta":{"label":"Explore Industries","href":"/industries"}}'::jsonb, 6 from public.pages where slug = '/industries/energy-petrochemical';
-- Maritime & Logistics
delete from public.sections where page_id = (select id from public.pages where slug = '/industries/maritime-logistics');
insert into public.sections (page_id, key, type, tone, data, position) select id, 'hero', 'heroSplit', NULL, '{"eyebrow":"Maritime & Logistics","heading":"SEO for Maritime and Logistics Operators","body":"Logistics buyers search by route, service and capability, often under time pressure. Being findable in that language is most of the job.","primaryCta":{"label":"Request a Visibility Review","href":"/contact"},"secondaryCta":{"label":"View Monthly SEO Packages","href":"/monthly-seo-packages"},"showcase":[{"kind":"roadmap","label":"How buyers search","title":"By Route and Capability","items":["A route and a mode","A port and a service","A vessel and a repair","Often under time pressure"]},{"kind":"coverage","label":"What it rests on","title":"Coverage and Compliance","items":["Ports served","Certifications","Response"]}]}'::jsonb, 0 from public.pages where slug = '/industries/maritime-logistics';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'who-this-is-for', 'cardGrid', 'surface', '{"variant":"compact","columns":3,"eyebrow":"Who This Is For","heading":"Operators This Applies To","body":"The kinds of business this applies to. Naming a category is not a claim of expertise in it.","cards":[{"title":"Port Services & Stevedoring","icon":"ship","body":"Searched by service and by port, with capability and certification usually deciding the shortlist."},{"title":"Freight Transport & Warehousing","icon":"network","body":"Route, mode and capacity drive the search, and comparison against several operators is standard."},{"title":"Marine Repair & Industrial Supplies","icon":"wrench","body":"Often urgent, because a vessel out of service is costing money every day it waits."}]}'::jsonb, 1 from public.pages where slug = '/industries/maritime-logistics';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'search-behaviour', 'featureSplit', 'white', '{"align":"right","eyebrow":"Search Behaviour","heading":"What Search Looks Like in Logistics","body":"Logistics search sits between the urgency of a trade and the caution of a procurement purchase. A freight buyer looking for a route and a mode will compare several operators before making contact, but a vessel needing repair is an emergency with a daily cost attached, and those two searches want completely different pages.\n\nThe vocabulary is precise. Routes, ports, vessel types, cargo classes and certifications are the terms people use, and a site organised around company departments rather than around those terms is hard to find no matter how good the business is. Reach varies enormously: a single-yard repair business competes locally, while a freight operator moving cargo across the region competes with operators in other cities for the same contract.","groups":[{"title":"Route, mode, capability","icon":"network","body":"Pages organised by what customers ship and where, rather than by internal department."},{"title":"Downtime makes some searches urgent","icon":"warning","body":"Repair and emergency service searches behave like a trade call, and need to be treated that way."},{"title":"Certifications are search terms","icon":"shield-check","body":"Compliance and accreditation are often the filter, so they belong on the page rather than in a PDF."}]}'::jsonb, 2 from public.pages where slug = '/industries/maritime-logistics';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'how-it-works', 'cardGrid', 'surface', '{"variant":"cards","columns":2,"eyebrow":"Where to Start","heading":"Two Ways In, Sorted by Reach","body":"The method does not change with the industry. What changes is the search language, the priorities, and what a single lead is worth. Which service fits a maritime & logistics business comes down to where it competes, not how big it is.","cards":[{"title":"Local SEO","icon":"map-pin","body":"For businesses competing for customers in a defined area, however many locations they run in it.","cta":{"label":"Explore Local SEO","href":"/local-seo-services"}},{"title":"Traditional SEO","icon":"globe","body":"For businesses competing across multiple markets, multiple service lines, or genuinely competitive search.","cta":{"label":"Explore Traditional SEO","href":"/traditional-seo-services"}}]}'::jsonb, 3 from public.pages where slug = '/industries/maritime-logistics';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'monthly-recap', 'reportingBlock', 'white', '{"eyebrow":"Reporting","heading":"The Monthly Recap","body":"The same four questions every month, whatever the industry.","did":"The specific work completed that month, named task by task.","why":"Why that work was the priority ahead of everything else in the queue.","changed":"What moved, reported honestly, including the months where little did.","next":"Next month''s priorities, so nothing in the following recap is a surprise.","cta":{"label":"See How JMC Reports SEO Progress","href":"/seo-reporting"}}'::jsonb, 4 from public.pages where slug = '/industries/maritime-logistics';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'faq', 'faq', 'surface', '{"eyebrow":"Questions","heading":"Maritime Questions","items":[{"question":"Do customers really find logistics providers through search?","answer":"For new suppliers and for urgent requirements, frequently. Long-standing contracts come through relationships, but the shortlist for a new route or an unplanned repair is very often built from a search."},{"question":"Should pages be built around routes or around services?","answer":"Both, usually, because they are searched differently. A service page explains capability; a route or port page catches the searches that name a specific place."},{"question":"How is an urgent repair enquiry handled differently?","answer":"Those searches need a fast, obvious path to a phone number and clear coverage information, which is closer to how a trades page works than to how a procurement page works."},{"question":"Which service fits a business like this?","answer":"It depends on reach rather than size. If the customers are in a defined area, that is Local SEO, however many locations are involved. If the business competes across several markets or service lines, that is Traditional SEO. A visibility review sorts it in one conversation."},{"question":"Does JMC specialise in maritime & logistics?","answer":"No, and that is deliberate. A specialist charges for pattern-matching from other clients in your sector, which JMC does not pretend to have yet. What is on offer instead is a method that works regardless of sector, and reporting clear enough that you can see whether it is working."}],"cta":{"label":"Request a Visibility Review","href":"/contact"}}'::jsonb, 5 from public.pages where slug = '/industries/maritime-logistics';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'final-cta', 'finalCta', NULL, '{"heading":"Start With a Visibility Review","body":"Where the business appears today, which searches it is missing, and which of those gaps is worth closing first.","primaryCta":{"label":"Request a Visibility Review","href":"/contact"},"secondaryCta":{"label":"Explore Industries","href":"/industries"}}'::jsonb, 6 from public.pages where slug = '/industries/maritime-logistics';
-- Commercial Construction & Infrastructure
delete from public.sections where page_id = (select id from public.pages where slug = '/industries/commercial-construction-infrastructure');
insert into public.sections (page_id, key, type, tone, data, position) select id, 'hero', 'heroSplit', NULL, '{"eyebrow":"Commercial Construction & Infrastructure","heading":"SEO for Commercial Construction Firms","body":"Commercial construction is won on capability, references and bid lists, but the shortlist is increasingly built by searching. Being on it starts with being findable.","primaryCta":{"label":"Request a Visibility Review","href":"/contact"},"secondaryCta":{"label":"View Monthly SEO Packages","href":"/monthly-seo-packages"},"showcase":[{"kind":"report","label":"How buyers search","title":"To Qualify, Not to Enquire","items":["Project type and sector","Scale and scope","Certifications held","Before any invitation"]},{"kind":"coverage","label":"What it rests on","title":"Evidence in Text","items":["Project pages","Capability","Standards met"]}]}'::jsonb, 0 from public.pages where slug = '/industries/commercial-construction-infrastructure';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'who-this-is-for', 'cardGrid', 'surface', '{"variant":"numbered","columns":3,"eyebrow":"Who This Is For","heading":"Contractors and Suppliers","body":"The kinds of business this applies to. Naming a category is not a claim of expertise in it.","cards":[{"title":"Commercial & Industrial Subcontractors","icon":"hard-hat","body":"Shortlisted on trade, project type and sector experience long before any bid conversation happens."},{"title":"Civil & Roadway Contracting","icon":"building","body":"Public and private procurement with long cycles and a heavy emphasis on qualification."},{"title":"Earthmoving, Crane & Site Services","icon":"layers","body":"Hired on equipment, capacity and availability, frequently at short notice on an active site."}]}'::jsonb, 1 from public.pages where slug = '/industries/commercial-construction-infrastructure';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'search-behaviour', 'featureSplit', 'white', '{"align":"left","eyebrow":"Search Behaviour","heading":"What Search Looks Like in Construction","body":"The searches that matter here rarely look like lead generation. An architect looking for a product that meets a standard, a developer checking whether a contractor has done a project of a given type before, a procurement team qualifying a supplier: all of them are searching, and none of them will fill in a contact form on the first visit.\n\nThat makes the project and capability pages the working part of a construction site. Sector, project type, scale and qualification are the terms people search, and a portfolio organised as a photo gallery answers none of them. The cycle is measured in months, competition runs regional to national, and the value of a single project means a small volume of exactly the right visitors is the goal rather than traffic.","groups":[{"title":"Qualification, not enquiry","icon":"clipboard-check","body":"Most visitors are checking whether you qualify. The site has to answer that without a conversation."},{"title":"Project type is the search term","icon":"search","body":"Sector and project pages do the ranking. A gallery of photographs does not."},{"title":"Specified before it is bought","icon":"file-text","body":"For suppliers, the decision often happens with the specifier rather than with the buyer."}]}'::jsonb, 2 from public.pages where slug = '/industries/commercial-construction-infrastructure';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'how-it-works', 'cardGrid', 'surface', '{"variant":"cards","columns":2,"eyebrow":"Where to Start","heading":"Two Ways In, Sorted by Reach","body":"The method does not change with the industry. What changes is the search language, the priorities, and what a single lead is worth. Which service fits a commercial construction & infrastructure business comes down to where it competes, not how big it is.","cards":[{"title":"Local SEO","icon":"map-pin","body":"For businesses competing for customers in a defined area, however many locations they run in it.","cta":{"label":"Explore Local SEO","href":"/local-seo-services"}},{"title":"Traditional SEO","icon":"globe","body":"For businesses competing across multiple markets, multiple service lines, or genuinely competitive search.","cta":{"label":"Explore Traditional SEO","href":"/traditional-seo-services"}}]}'::jsonb, 3 from public.pages where slug = '/industries/commercial-construction-infrastructure';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'monthly-recap', 'reportingBlock', 'white', '{"eyebrow":"Reporting","heading":"The Monthly Recap","body":"The same four questions every month, whatever the industry.","did":"The specific work completed that month, named task by task.","why":"Why that work was the priority ahead of everything else in the queue.","changed":"What moved, reported honestly, including the months where little did.","next":"Next month''s priorities, so nothing in the following recap is a surprise.","cta":{"label":"See How JMC Reports SEO Progress","href":"/seo-reporting"}}'::jsonb, 4 from public.pages where slug = '/industries/commercial-construction-infrastructure';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'faq', 'faq', 'surface', '{"eyebrow":"Questions","heading":"Construction Questions","items":[{"question":"Does SEO matter when work comes through bid lists?","answer":"Yes, because getting onto the list increasingly involves being found and checked first. Firms are researched before they are invited, and a thin website removes you from consideration quietly."},{"question":"What should a project portfolio actually contain?","answer":"Project type, sector, scale and scope written as text, not only photographs. That is what people search for, and images alone cannot be read as an answer to it."},{"question":"How long is the payback in this sector?","answer":"Longer than in consumer categories, because the cycle itself is long. The recap tracks visibility and qualification-stage movement in the meantime rather than pretending an enquiry count tells the whole story."},{"question":"Which service fits a business like this?","answer":"It depends on reach rather than size. If the customers are in a defined area, that is Local SEO, however many locations are involved. If the business competes across several markets or service lines, that is Traditional SEO. A visibility review sorts it in one conversation."},{"question":"Does JMC specialise in commercial construction & infrastructure?","answer":"No, and that is deliberate. A specialist charges for pattern-matching from other clients in your sector, which JMC does not pretend to have yet. What is on offer instead is a method that works regardless of sector, and reporting clear enough that you can see whether it is working."}],"cta":{"label":"Request a Visibility Review","href":"/contact"}}'::jsonb, 5 from public.pages where slug = '/industries/commercial-construction-infrastructure';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'final-cta', 'finalCta', NULL, '{"heading":"Start With a Visibility Review","body":"Where the business appears today, which searches it is missing, and which of those gaps is worth closing first.","primaryCta":{"label":"Request a Visibility Review","href":"/contact"},"secondaryCta":{"label":"Explore Industries","href":"/industries"}}'::jsonb, 6 from public.pages where slug = '/industries/commercial-construction-infrastructure';
-- Aerospace & Aviation
delete from public.sections where page_id = (select id from public.pages where slug = '/industries/aerospace-aviation');
insert into public.sections (page_id, key, type, tone, data, position) select id, 'hero', 'heroSplit', NULL, '{"eyebrow":"Aerospace & Aviation","heading":"SEO for Aerospace and Aviation Suppliers","body":"Aerospace buyers search by part, standard and certification, and they qualify before they contact. The work is being findable and credible in that order.","primaryCta":{"label":"Request a Visibility Review","href":"/contact"},"secondaryCta":{"label":"View Monthly SEO Packages","href":"/monthly-seo-packages"},"showcase":[{"kind":"coverage","label":"How buyers search","title":"By Part and Approval","items":["Part numbers","Materials and specifications","Certifications first","Across several weeks"]},{"kind":"coverage","label":"What it rests on","title":"Findable Detail","items":["Crawlable pages","Named approvals","Published ranges"]}]}'::jsonb, 0 from public.pages where slug = '/industries/aerospace-aviation';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'who-this-is-for', 'cardGrid', 'surface', '{"variant":"split","columns":3,"eyebrow":"Who This Is For","heading":"Suppliers This Applies To","body":"The kinds of business this applies to. Naming a category is not a claim of expertise in it.","cards":[{"title":"Aviation Services & Hangar Operations","icon":"plane","body":"Capability, certification and location together decide who gets contacted."},{"title":"Aerospace Manufacturing & Parts Suppliers","icon":"factory","body":"Found by part number, material and specification, frequently by an engineer rather than a buyer."},{"title":"Defense & Space Contracting","icon":"shield-check","body":"Clearance, compliance and past performance are the first filters applied, before capability."}]}'::jsonb, 1 from public.pages where slug = '/industries/aerospace-aviation';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'search-behaviour', 'featureSplit', 'white', '{"align":"right","eyebrow":"Search Behaviour","heading":"What Search Looks Like in Aerospace","body":"Aerospace is the clearest example of search as qualification rather than as marketing. A procurement manager comparing specifications over six weeks is not going to be moved by a headline, and an engineer searching for a part number either finds a page carrying that number or does not. Certification is often the first filter applied, before capability and long before price.\n\nThe practical consequence is that the searchable surface of a supplier''s site is usually far too small. Capabilities live in a PDF, part ranges live in a table nobody can crawl, and approvals are named on an about page rather than where they would be searched for. Fixing that is unglamorous work with an unusually direct effect, and the competition for it is national rather than local.","groups":[{"title":"Certification filters first","icon":"shield-check","body":"Approvals belong on crawlable pages, not only inside a downloadable document."},{"title":"Part numbers are queries","icon":"search","body":"If a range only exists inside a PDF or a script-driven table, it cannot be found."},{"title":"Weeks of comparison before contact","icon":"calendar","body":"The site is doing the selling during a period when nobody is talking to you."}]}'::jsonb, 2 from public.pages where slug = '/industries/aerospace-aviation';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'how-it-works', 'cardGrid', 'surface', '{"variant":"cards","columns":2,"eyebrow":"Where to Start","heading":"Two Ways In, Sorted by Reach","body":"The method does not change with the industry. What changes is the search language, the priorities, and what a single lead is worth. Which service fits a aerospace & aviation business comes down to where it competes, not how big it is.","cards":[{"title":"Local SEO","icon":"map-pin","body":"For businesses competing for customers in a defined area, however many locations they run in it.","cta":{"label":"Explore Local SEO","href":"/local-seo-services"}},{"title":"Traditional SEO","icon":"globe","body":"For businesses competing across multiple markets, multiple service lines, or genuinely competitive search.","cta":{"label":"Explore Traditional SEO","href":"/traditional-seo-services"}}]}'::jsonb, 3 from public.pages where slug = '/industries/aerospace-aviation';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'monthly-recap', 'reportingBlock', 'white', '{"eyebrow":"Reporting","heading":"The Monthly Recap","body":"The same four questions every month, whatever the industry.","did":"The specific work completed that month, named task by task.","why":"Why that work was the priority ahead of everything else in the queue.","changed":"What moved, reported honestly, including the months where little did.","next":"Next month''s priorities, so nothing in the following recap is a surprise.","cta":{"label":"See How JMC Reports SEO Progress","href":"/seo-reporting"}}'::jsonb, 4 from public.pages where slug = '/industries/aerospace-aviation';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'faq', 'faq', 'surface', '{"eyebrow":"Questions","heading":"Aerospace & Aviation Questions","items":[{"question":"Is search volume high enough to be worth the work?","answer":"Volume is low and value is very high, so the goal is not traffic. A narrow set of technical searches, found by the right handful of people, is what the tracked keyword set is built around."},{"question":"What about content that cannot be published?","answer":"Plenty in this sector is restricted, and none of it needs publishing. The gains usually come from making already-public capability, approvals and part information properly findable."},{"question":"Is a supplier competing locally or nationally?","answer":"Almost always nationally, which puts most aerospace suppliers in the Traditional lane. A ground services business tied to one airport is the exception, and it is a Local engagement."},{"question":"Which service fits a business like this?","answer":"It depends on reach rather than size. If the customers are in a defined area, that is Local SEO, however many locations are involved. If the business competes across several markets or service lines, that is Traditional SEO. A visibility review sorts it in one conversation."},{"question":"Does JMC specialise in aerospace & aviation?","answer":"No, and that is deliberate. A specialist charges for pattern-matching from other clients in your sector, which JMC does not pretend to have yet. What is on offer instead is a method that works regardless of sector, and reporting clear enough that you can see whether it is working."}],"cta":{"label":"Request a Visibility Review","href":"/contact"}}'::jsonb, 5 from public.pages where slug = '/industries/aerospace-aviation';
insert into public.sections (page_id, key, type, tone, data, position) select id, 'final-cta', 'finalCta', NULL, '{"heading":"Start With a Visibility Review","body":"Where the business appears today, which searches it is missing, and which of those gaps is worth closing first.","primaryCta":{"label":"Request a Visibility Review","href":"/contact"},"secondaryCta":{"label":"Explore Industries","href":"/industries"}}'::jsonb, 6 from public.pages where slug = '/industries/aerospace-aviation';
-- ---------------------------------------------------------- packages ----
-- Upserted, not deleted and rebuilt: a tier hidden or repriced in /admin
-- keeps its row, and only the fields below are refreshed.
insert into public.packages (id, group_key, name, price, price_unit, onboarding_fee, term, positioning, timeline, best_fit, deliverables, cta_label, cta_href, featured, visible, pricing_pending, position) values (
  'local-off-page-essentials', 'local', 'Off-Page Essentials', '$399', '/month', '$199 one-time', NULL, NULL, NULL,
  'Best for businesses that need a stronger local visibility foundation without committing to a full local SEO campaign.', ARRAY['Citation and business listing support', 'Google Business Profile support', 'NAP consistency cleanup and local presence maintenance', 'Foundational off-page SEO support', 'Monthly reporting and visibility summary']::text[],
  'Request a Visibility Review', '/contact', false, false, false, 0)
on conflict (id) do update set
  name = excluded.name, price = excluded.price,
  price_unit = excluded.price_unit, onboarding_fee = excluded.onboarding_fee,
  term = excluded.term, positioning = excluded.positioning,
  timeline = excluded.timeline, best_fit = excluded.best_fit,
  deliverables = excluded.deliverables,
  cta_label = excluded.cta_label, cta_href = excluded.cta_href,
  featured = excluded.featured;
insert into public.packages (id, group_key, name, price, price_unit, onboarding_fee, term, positioning, timeline, best_fit, deliverables, cta_label, cta_href, featured, visible, pricing_pending, position) values (
  'local-neighborhood', 'local', 'Neighborhood', '$875', '/month', '$349 one-time', '12-month term, then month to month', 'Local Foundation', NULL,
  'Best for businesses focused on improving visibility in one primary service area.', ARRAY['30 tracked keywords', '3 tracked competitors', '8 Google Business Profile posts per month', 'Up to 10 citations per month', '2 review request sends per month', 'Up to 15 review replies per month', 'Up to 2 Strategic SEO Pages per month', 'Local search grid tracking', 'Monthly Recap and Quarterly Project Update']::text[],
  'Start with Neighborhood', '/contact?tier=neighborhood', false, true, false, 1)
on conflict (id) do update set
  name = excluded.name, price = excluded.price,
  price_unit = excluded.price_unit, onboarding_fee = excluded.onboarding_fee,
  term = excluded.term, positioning = excluded.positioning,
  timeline = excluded.timeline, best_fit = excluded.best_fit,
  deliverables = excluded.deliverables,
  cta_label = excluded.cta_label, cta_href = excluded.cta_href,
  featured = excluded.featured;
insert into public.packages (id, group_key, name, price, price_unit, onboarding_fee, term, positioning, timeline, best_fit, deliverables, cta_label, cta_href, featured, visible, pricing_pending, position) values (
  'local-citywide', 'local', 'Citywide', '$1,165', '/month', '$449 one-time', '12-month term, then month to month', 'City-Level Growth', NULL,
  'Best for businesses competing more aggressively across a city-level market with broader content and review support.', ARRAY['45 tracked keywords', '5 tracked competitors', '12 Google Business Profile posts per month', 'Up to 15 citations per month', '4 review request sends per month', 'Up to 20 review replies per month', 'Up to 3 Strategic SEO Pages per month', 'Local search grid tracking', 'Monthly Recap and Quarterly Project Update']::text[],
  'Start with Citywide', '/contact?tier=citywide', true, true, false, 2)
on conflict (id) do update set
  name = excluded.name, price = excluded.price,
  price_unit = excluded.price_unit, onboarding_fee = excluded.onboarding_fee,
  term = excluded.term, positioning = excluded.positioning,
  timeline = excluded.timeline, best_fit = excluded.best_fit,
  deliverables = excluded.deliverables,
  cta_label = excluded.cta_label, cta_href = excluded.cta_href,
  featured = excluded.featured;
insert into public.packages (id, group_key, name, price, price_unit, onboarding_fee, term, positioning, timeline, best_fit, deliverables, cta_label, cta_href, featured, visible, pricing_pending, position) values (
  'local-metro', 'local', 'Metro', '$1,695', '/month', '$649 one-time', '12-month term, then month to month', 'Metro Expansion', NULL,
  'Designed for businesses competing across multiple cities or high-demand metro areas where consistent content, visibility, and reputation signals are required to gain market share.', ARRAY['60 tracked keywords', '5 tracked competitors', '16 Google Business Profile posts per month', 'Up to 25 citations per month', '4 review request sends per month', 'Up to 20 review replies per month', 'Up to 4 Strategic SEO Pages per month', 'Local search grid tracking', 'Monthly Recap and Quarterly Project Update']::text[],
  'Start with Metro', '/contact?tier=metro', false, true, false, 3)
on conflict (id) do update set
  name = excluded.name, price = excluded.price,
  price_unit = excluded.price_unit, onboarding_fee = excluded.onboarding_fee,
  term = excluded.term, positioning = excluded.positioning,
  timeline = excluded.timeline, best_fit = excluded.best_fit,
  deliverables = excluded.deliverables,
  cta_label = excluded.cta_label, cta_href = excluded.cta_href,
  featured = excluded.featured;
insert into public.packages (id, group_key, name, price, price_unit, onboarding_fee, term, positioning, timeline, best_fit, deliverables, cta_label, cta_href, featured, visible, pricing_pending, position) values (
  'traditional-regional', 'traditional', 'Regional', '$2,295', '/month', '$895 one-time', '12-month term, then month to month', 'Multi-Market Foundation', NULL,
  'Best for businesses targeting 1 to 3 priority markets or a defined regional service footprint.', ARRAY['Up to 60 tracked keywords', 'Up to 5 tracked competitors', 'Up to 2 Strategic SEO Pages per month', 'Technical SEO monitoring and issue flagging', 'Authority-building strategy recommendations', 'Monthly dashboard reporting', 'Monthly Recap and Quarterly Project Update']::text[],
  'Start with Regional', '/contact?tier=regional', false, true, false, 4)
on conflict (id) do update set
  name = excluded.name, price = excluded.price,
  price_unit = excluded.price_unit, onboarding_fee = excluded.onboarding_fee,
  term = excluded.term, positioning = excluded.positioning,
  timeline = excluded.timeline, best_fit = excluded.best_fit,
  deliverables = excluded.deliverables,
  cta_label = excluded.cta_label, cta_href = excluded.cta_href,
  featured = excluded.featured;
insert into public.packages (id, group_key, name, price, price_unit, onboarding_fee, term, positioning, timeline, best_fit, deliverables, cta_label, cta_href, featured, visible, pricing_pending, position) values (
  'traditional-national', 'traditional', 'National', '$3,495', '/month', '$1,095 one-time', '12-month term, then month to month', 'National Growth', NULL,
  'Best for businesses targeting broader multi-market visibility across larger service areas, multiple service lines, or more competitive search markets.', ARRAY['Up to 75 tracked keywords', 'Up to 8 tracked competitors', 'Up to 3 Strategic SEO Pages per month', 'Technical SEO monitoring and issue flagging', 'Authority-building strategy recommendations', 'Monthly dashboard reporting', 'Monthly Recap and Quarterly Project Update']::text[],
  'Start with National', '/contact?tier=national', true, true, false, 5)
on conflict (id) do update set
  name = excluded.name, price = excluded.price,
  price_unit = excluded.price_unit, onboarding_fee = excluded.onboarding_fee,
  term = excluded.term, positioning = excluded.positioning,
  timeline = excluded.timeline, best_fit = excluded.best_fit,
  deliverables = excluded.deliverables,
  cta_label = excluded.cta_label, cta_href = excluded.cta_href,
  featured = excluded.featured;
insert into public.packages (id, group_key, name, price, price_unit, onboarding_fee, term, positioning, timeline, best_fit, deliverables, cta_label, cta_href, featured, visible, pricing_pending, position) values (
  'traditional-national-plus', 'traditional', 'National+', '$5,295', '/month', '$1,295 one-time', '12-month term, then month to month', 'Competitive Expansion', NULL,
  'Best for larger brands, complex service organizations, or high-competition industries that need broader search coverage and a more aggressive growth plan.', ARRAY['Up to 90 tracked keywords', 'Up to 10 tracked competitors', 'Up to 4 Strategic SEO Pages per month', 'Technical SEO monitoring and issue flagging', 'Authority-building strategy recommendations', 'Monthly dashboard reporting', 'Monthly Recap and Quarterly Project Update']::text[],
  'Start with National+', '/contact?tier=national-plus', false, true, false, 6)
on conflict (id) do update set
  name = excluded.name, price = excluded.price,
  price_unit = excluded.price_unit, onboarding_fee = excluded.onboarding_fee,
  term = excluded.term, positioning = excluded.positioning,
  timeline = excluded.timeline, best_fit = excluded.best_fit,
  deliverables = excluded.deliverables,
  cta_label = excluded.cta_label, cta_href = excluded.cta_href,
  featured = excluded.featured;
insert into public.packages (id, group_key, name, price, price_unit, onboarding_fee, term, positioning, timeline, best_fit, deliverables, cta_label, cta_href, featured, visible, pricing_pending, position) values (
  'real-estate-agent', 'realEstate', 'Agent Growth SEO', 'Contact for pricing', NULL, NULL, NULL, NULL, NULL,
  'Built for individual agents who need stronger personal visibility in their market and content that supports trust with buyers and sellers.', ARRAY['Google Business Profile and local visibility support', 'Neighborhood and market content strategy', 'Agent website structure and page improvements', 'Review and trust signal support', 'Search visibility tracking', 'Monthly Recap and reporting']::text[],
  'Request a Visibility Review', '/contact', false, false, true, 7)
on conflict (id) do update set
  name = excluded.name, price = excluded.price,
  price_unit = excluded.price_unit, onboarding_fee = excluded.onboarding_fee,
  term = excluded.term, positioning = excluded.positioning,
  timeline = excluded.timeline, best_fit = excluded.best_fit,
  deliverables = excluded.deliverables,
  cta_label = excluded.cta_label, cta_href = excluded.cta_href,
  featured = excluded.featured;
insert into public.packages (id, group_key, name, price, price_unit, onboarding_fee, term, positioning, timeline, best_fit, deliverables, cta_label, cta_href, featured, visible, pricing_pending, position) values (
  'real-estate-team', 'realEstate', 'Team and Brokerage Growth SEO', 'Contact for pricing', NULL, NULL, NULL, NULL, NULL,
  'Built for teams and brokerages that need scalable visibility across multiple agents, markets, and neighborhoods.', ARRAY['Multi-market local visibility strategy', 'Neighborhood and market authority content', 'Site structure for teams and agent rosters', 'Review and reputation support at scale', 'Search visibility tracking across markets', 'Monthly Recap and reporting']::text[],
  'Request a Visibility Review', '/contact', false, false, true, 8)
on conflict (id) do update set
  name = excluded.name, price = excluded.price,
  price_unit = excluded.price_unit, onboarding_fee = excluded.onboarding_fee,
  term = excluded.term, positioning = excluded.positioning,
  timeline = excluded.timeline, best_fit = excluded.best_fit,
  deliverables = excluded.deliverables,
  cta_label = excluded.cta_label, cta_href = excluded.cta_href,
  featured = excluded.featured;
insert into public.packages (id, group_key, name, price, price_unit, onboarding_fee, term, positioning, timeline, best_fit, deliverables, cta_label, cta_href, featured, visible, pricing_pending, position) values (
  'sprint-neighborhood', 'sprint', 'Neighborhood Launch Sprint', '$799', 'one-time', NULL, NULL, NULL, '30 days',
  'For businesses that need a stronger local SEO foundation before moving into ongoing monthly service.', ARRAY['Kickoff and access setup', 'Local SEO audit with priority findings', 'Local keyword and competitor snapshot', 'Google Search Console and Bing setup or verification', 'Google Business Profile audit and core optimization', 'Citation audit and NAP standard', 'Schema, sitemap, and robots.txt review', 'Titles and meta descriptions for up to 5 priority pages', 'Local search grid baseline snapshot', '30-Day Action Roadmap']::text[],
  'Start the Neighborhood Sprint', '/contact?type=sprint', false, true, false, 9)
on conflict (id) do update set
  name = excluded.name, price = excluded.price,
  price_unit = excluded.price_unit, onboarding_fee = excluded.onboarding_fee,
  term = excluded.term, positioning = excluded.positioning,
  timeline = excluded.timeline, best_fit = excluded.best_fit,
  deliverables = excluded.deliverables,
  cta_label = excluded.cta_label, cta_href = excluded.cta_href,
  featured = excluded.featured;
insert into public.packages (id, group_key, name, price, price_unit, onboarding_fee, term, positioning, timeline, best_fit, deliverables, cta_label, cta_href, featured, visible, pricing_pending, position) values (
  'sprint-regional', 'sprint', 'Regional Launch Sprint', '$1,495', 'one-time', NULL, NULL, NULL, '30 days',
  'For businesses targeting a broader service region or multiple markets that want a strong foundation before starting monthly service.', ARRAY['Kickoff and access setup', 'Technical and on-page SEO audit', 'Regional keyword and competitor analysis', 'Google Search Console and Bing setup or verification', 'Schema, sitemap, and robots.txt review', 'Titles and meta descriptions for up to 10 priority pages', 'Backlink audit', '30-Day Roadmap and next-step recommendations']::text[],
  'Start the Regional Sprint', '/contact?type=sprint', false, true, false, 10)
on conflict (id) do update set
  name = excluded.name, price = excluded.price,
  price_unit = excluded.price_unit, onboarding_fee = excluded.onboarding_fee,
  term = excluded.term, positioning = excluded.positioning,
  timeline = excluded.timeline, best_fit = excluded.best_fit,
  deliverables = excluded.deliverables,
  cta_label = excluded.cta_label, cta_href = excluded.cta_href,
  featured = excluded.featured;

commit;
